Replacing selectattr('tls', 'true'|'false') with selectattr('tls', 'e…
linux-system-roles/logging pull request #169
Opened 2020-08-18 19:00 UTC by nhosoi

…q', True|False).

In the jinja2 doc:
true(value) and false(value) are "New in version 2.11."

2020-08-19 08:26 UTC, pcahyna commented
I am afraid that this will not work in older Jinja2: https://github.com/linux-system-roles/storage/issues/49

2020-08-19 14:10 UTC, nhosoi commented
> I am afraid that this will not work in older Jinja2: [linux-system-roles/storage#49](https://github.com/linux-system-roles/storage/issues/49)

(;_;) Thanks for your input, @pcahyna.  Replacing 'eq' with '=='.

2020-08-19 14:40 UTC, pcahyna commented
@nhosoi please verify that it actually works with Jinja 2.7, you can use RHEL 7 or CentOS 7 as a control host for that

2020-08-19 21:51 UTC, richm commented
> @nhosoi please verify that it actually works with Jinja 2.7, you can use RHEL 7 or CentOS 7 as a control host for that

I don't think it works there either.  In fact, I think there is a lot of code that won't work with jinja2 2.7.  I think `selectattr('foo','==','something')` will not work with jinja2 2.7.

One easy way to test is with a venv:
python3 -mvenv .venv
. .venv/bin/activate
pip install 'ansible<2.9' 'jinja2<2.8'
ansible-playbook -vv some-playbook-that-uses-selectattr-and-==.yml
```

2020-08-19 23:57 UTC, nhosoi commented
Thanks, @richm. Confirmed `selectattr('foo','==','something')` does not work with `ansible 2.8.14` & `Jinja2 2.7.3`.
```
TASK [linux-system-roles.logging : Set rsyslog_output_elasticsearch for the omelasticsearch output] ***
task path: /home/nhosoi/linux-system-roles/logging/tests/roles/linux-system-roles.logging/tasks/main.yml:5
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: jinja2.exceptions.TemplateRuntimeError: no test named '=='
fatal: [/home/nhosoi/Downloads/CentOS-7-x86_64-GenericCloud.qcow2c]: FAILED! => {}
MSG:
Unexpected failure during module execution.
```
Sadly, replacing `==` with `equalto` did not solve the error, either.

Logging role is the one that uses selectattr most (not just in this PR, but it's been in the code for a long time...). Should we replace it with something backward compatible???

But I think @richm is right. There should be more cases which do not work with `ansible 2.8.14` & `Jinja2 2.7.3`.  For instance, I ran certificate/tests_basic_self_signed.yml and ran it with `ansible 2.8.14` & `Jinja2 2.7.3`, which failed like this. Even `namespace` is not available in jinja2 2.7...
```
TASK [linux-system-roles.certificate : Ensure provider packages are installed] ********************
task path: /home/nhosoi/linux-system-roles/certificate/tasks/main.yml:34
fatal: [/home/nhosoi/Downloads/CentOS-7-x86_64-GenericCloud.qcow2c]: FAILED! => {}
MSG:
'namespace' is undefined

```

2020-08-20 00:09 UTC, nhosoi commented
BTW, I'm wondering why this molecule failure has started. I can reproduce it with "tox -e molecule". Again, this is likely a version issue since if I run "tox -e molecule" with `ansible 2.8.14` &`Jinja2 2.7.3`, I don't see this error...
```
--> Executing Ansible Lint on /home/travis/build/linux-system-roles/logging/tests/tests_default.yml...
Traceback (most recent call last):
  File "/home/travis/build/linux-system-roles/logging/.tox/env-3.6/bin/ansible-lint", line 8, in <module>
    sys.exit(main())
  File "/home/travis/build/linux-system-roles/logging/.tox/env-3.6/lib/python3.6/site-packages/ansiblelint/__main__.py", line 123, in main
    options.verbosity, checked_files)
  File "/home/travis/build/linux-system-roles/logging/.tox/env-3.6/lib/python3.6/site-packages/ansiblelint/runner.py", line 43, in __init__
    self._update_exclude_paths(exclude_paths)
  File "/home/travis/build/linux-system-roles/logging/.tox/env-3.6/lib/python3.6/site-packages/ansiblelint/runner.py", line 52, in _update_exclude_paths
    paths = ansiblelint.utils.expand_paths_vars(exclude_paths)
  File "/home/travis/build/linux-system-roles/logging/.tox/env-3.6/lib/python3.6/site-packages/ansiblelint/utils.py", line 783, in expand_paths_vars
    paths = [expand_path_vars(p) for p in paths]
  File "/home/travis/build/linux-system-roles/logging/.tox/env-3.6/lib/python3.6/site-packages/ansiblelint/utils.py", line 783, in <listcomp>
    paths = [expand_path_vars(p) for p in paths]
  File "/home/travis/build/linux-system-roles/logging/.tox/env-3.6/lib/python3.6/site-packages/ansiblelint/utils.py", line 775, in expand_path_vars
    path = path.strip()
AttributeError: 'PosixPath' object has no attribute 'strip'
ERROR: InvocationError for command /bin/bash .travis/runsyspycmd.sh molecule lint -s default (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   molecule: commands failed
```

2020-08-20 06:56 UTC, pcahyna commented
@nhosoi, concerning the last problem: @i386x said in chat: ansible-lint issue is fixed in upstream now: https://github.com/ansible/ansible-lint/commit/5b5c000ff2d8d986b40d8075b0948f81a560ff03

2020-08-20 07:00 UTC, pcahyna approved these changes
Ready to merge? This will solve compatibility with Jinja 2.10 and 2.7 will have to be solved later.

2020-08-20 07:04 UTC, pcahyna commented
one more comment: `true` and `false` in Jinja 2 are lowercase, although upercase versions work as well, they are not preferred. https://jinja.palletsprojects.com/en/2.10.x/templates/#literals

2020-08-20 14:02 UTC, nhosoi commented
> Ready to merge? This will solve compatibility with Jinja 2.10 and 2.7 will have to be solved later.

If that's the case, we could close this pr and live with selectattr('tls', 'true'|'false'), right? If ok with you, closing this.

2020-08-20 14:16 UTC, pcahyna commented
> > Ready to merge? This will solve compatibility with Jinja 2.10 and 2.7 will have to be solved later.
> 
> If that's the case, we could close this pr and live with selectattr('tls', 'true'|'false'), right? If ok with you, closing this.

No, we need to support 2.10, the true/false tests were added in 2.11. Or have you verified that the true/false tests work in RHEL 8?

2020-08-20 14:20 UTC, pcahyna requested changes
`true` and `false` should be lowercase

2020-08-20 16:10 UTC, merged

2020-08-20 16:11 UTC, nhosoi commented
Thank you, @richm.  Merged!